{% set name = "pysbol3" %}
{% set pip_name = "sbol3" %}
{% set version = "1.0a6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pip_name[0] }}/{{ pip_name }}/{{ pip_name }}-{{ version }}.tar.gz
  sha256: 523656465274ff027b575da553b2e11c7c0cf853d4016d9edbb513eb8dbf182b

build:
  skip: true  # [py<36]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - python-dateutil
    - rdflib >=5.0
    - rdflib-jsonld

test:
  imports:
    - sbol3
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/SynBioDex/pySBOL3
  summary: Python implementation of SBOL 3 standard
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - tduigou
